---
title: "200429_qPCR7_mcmc_clean"
author: "Maximiliana Bogan"
date: "4/29/2020"
output: html_document
---

#install packages
```{r}
#install.packages('MCMC.qpcr')
#install.packages('tidyverse')
#install.packages("patchwork")
#install.packages("ggpubr")
```

#load libraries
```{r}
library(MCMC.qpcr)
library(tidyverse)
library(ggplot2)
library(gplots)
library(ggpubr)
library(patchwork)
```

#load data
```{r}
data <-read.csv(file = "qPCR7_clean_count.csv")

#force counts to be numeric
data$count <- as.numeric(data$count) 

#visualize to ensure data was imported properly
head(data) 
```

#set your reference level for each fixed factor (this example is for 1 way)
```{r}
levels(data$tissue)
data$tissue = relevel(data$tissue, ref='Sd')   
```

#run naive model
```{r}
#run model, with "individual" as a random factor to control for differences in reverse transcription or template loading between individual samples, pr = TRUE" removes outliers
naive_model=mcmc.qpcr(data=data, fixed="tissue", random = "individual", pr=TRUE, nitt=110000, thin=100, burnin=10000) 

#summarize p values not corrected for multiple hypothesis testing
summary(naive_model) 
```

#conduct pair-wise comparisons of p-values
```{r}
#shows absolute abundances
pwp_1way= HPDsummary(model=naive_model, data=data)

#retrieve bundles of data that can be used for more plotting (means, sds, CIs)
pwp_1way$summary  

#yield table of pair-wise p vals
pwp_1way$geneWise 
```

#plot results of your model
```{r}
#trellis plot WITHOUT reference gene
target_genes<-"sxph"
plot_naive_1way_target=HPDsummary(naive_model,data,xgroup="tissue", genes=target_genes) 
trellisByGene(plot_naive_1way_target, xFactor="tissue", groupFactor="tissue")+xlab("Tissue type")
```

#get normalized data
```{r}
nd=getNormalizedData(naive_model,data=data)
nd_combined = cbind(nd$conditions, nd$normData)
```

#plot in boxplot
```{r}
plt <- ggboxplot(nd_combined, x="tissue", y="sxph", fill="tissue") +
        theme_bw() +
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.border = element_rect(size = 1, color="black"), 
              plot.title = element_text(hjust = 0.5)) +
        ggtitle("Relative saxiphilin abundance") +
        xlab("tissue") +
        ylab("log2(abundance)") +
        geom_dotplot(aes(fill = tissue), 
                     binaxis='y', 
                     stackdir='center', 
                     dotsize = 0.7, 
                     position = position_dodge(0.8))

plt
```



